import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import StoreItem from '../components/ListItem'
import axios from 'axios'

interface PageProps {
  id: string,
  name: string,
  image: string,
};

const Home: NextPage = ({ data }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>foodmapv2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {
          data.map((store: PageProps) => (
            <StoreItem key={store.id} id={store.id} name={store.name} image={store.image} />
          ))
        }
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

async function getServerSideProps({ params }: any) {
  const req = await axios.get(`${process.env.API_ROOT}/api`);

  if (req.status != 200) throw "Store not found.";

  const data = req.data.map((obj: any) => {
    return {
      id: obj._id,
      name: obj.name,
      image: obj.image,
    }
  });

  return {
    props: { data: data }
  }

}

export { getServerSideProps };
export default Home
